### ISSUE TITLE
unhandled type 14 when converting from -oB to -oANY

### ISSUE THREAD

**Issue by kotee4ko** [bi-zone/masscan-ng#3]
When we writing to -oB we doing: [This](https://github.com/bi-zone/masscan-ng/blob/98429231d5124e78c852cf5b0733856375481c38/src/out-binary.c#L356)

Which is cost int 14 defined [here](https://github.com/bi-zone/masscan-ng/blob/98429231d5124e78c852cf5b0733856375481c38/src/out-record.h#L16)

But, when we reading from -oB (for example: --readscan out.raw -oG - ) we just doesn't handle it at all as I see [here](https://github.com/bi-zone/masscan-ng/blob/98429231d5124e78c852cf5b0733856375481c38/src/in-binary.c#L524)

So, the question is why sign of type 14, **from time to time**, appear in the binary output and breaking parser when converting? 

Thanks.

**Comment by sc07kvm** [comment]
I fixed it. You can check.
