### ISSUE TITLE
 found=0

### ISSUE THREAD

**Issue by sec13b** [bi-zone/masscan-ng#6]
./masscan-ng -iL ip.txt -p 80--exclude 1.2.3.4 --rate 4000 -oG 80.txt --open

Starting masscan-ng 1.3.2 (https://github.com/bi-zone/masscan-ng) at 2023-03-07 14:55:44 GMT
 -- forced options: -sS -Pn -n --randomize-hosts -v --send-eth
Initiating SYN Stealth Scan
Scanning 8571018 hosts [1 port/host]
[+] THREAD: recv: starting main loop. Count handle threads 1.
[+] wait recv threads
[receive_scheduler_thread]tcpcon_timeouts remaining, found=0, 0-tcbs, 0-tr_queue, 0-recv_queue, 0.00-t_recv       
[receive_handle_thread]tcpcon_timeouts
[receive_scheduler_thread]tcpcon_timeouts remaining, found=0, 0-tcbs, 0-tr_queue, 0-recv_queue, 0.00-t_recv     
[receive_handle_thread]tcpcon_timeouts
^Cwaiting several seconds to exit...34:41 remaining, found=0, 0-tcbs, 0-tr_queue, 0-recv_queue, 0.00-t_recv      
saving resume file to: paused.conf                                      
^Cte:  0.00-kpps,  1.52% done, waiting 10-secs, found=0, 0-tcbs, 0-tr_queue, 0-recv_queue, 0.00-t_recv     
ERROR: threads not exiting 1
^Cte:  0.00-kpps,  1.52% done, waiting 9-secs, found=0, 0-tcbs, 0-tr_queue, 1-recv_queue, 1.18-t_recv     
ERROR: threads not exiting 1

**Comment by kotee4ko** [comment]
-p 80--exclude

**Comment by sec13b** [comment]
[sudo] password for kali: 
[-] _parser_next(): unknown coding failure
ERROR: bad exclude address/range: --rate
ERROR: bad IP address/range: 4000
CONF: set config option error: range=4000
